name: 'Rails Tests'
description: 'Runs the tests for a Ruby on Rails application'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  services:
    postgres:
      image: postgres:11-alpine
      ports:
        - "5432:5432"
      env:
        POSTGRES_DB: rails_test
        POSTGRES_USER: rails
        POSTGRES_PASSWORD: password
  env:
    RAILS_ENV: test
    DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
        # Add or replace dependency steps here
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
      with:
        bundler-cache: true
          # Add or replace database setup steps here
    - name: Set up database schema
      run: bin/rails db:schema:load
        # Add or replace test runners here
    - name: Run tests
      run: bin/rake
